changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} — {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '- {{.Body}}'
kinds:
  - label: Added
  - label: Changed
  - label: Deprecated
  - label: Removed
  - label: Fixed
  - label: Security
custom:
  - key: App
    type: string
    optional: true
    label: App ID (if scoped to one app, e.g. nextcloud)
